use super::RecordType;

pub mod actor_values;
pub mod condition;
pub mod destruction;
pub mod effect;
pub mod equipment_type;
pub mod item;
pub mod model;
pub mod object_bounds;
pub mod script;
pub mod skill;
pub mod sound_level;
pub mod xnam;

pub const HEDR: RecordType = RecordType::new(b"HEDR");
pub const MAST: RecordType = RecordType::new(b"MAST");
pub const OFST: RecordType = RecordType::new(b"OFST");
pub const DELE: RecordType = RecordType::new(b"DELE");
pub const NAME: RecordType = RecordType::new(b"NAME");
pub const CNAM: RecordType = RecordType::new(b"CNAM");
pub const SNAM: RecordType = RecordType::new(b"SNAM");
pub const ONAM: RecordType = RecordType::new(b"ONAM");
pub const DNAM: RecordType = RecordType::new(b"DNAM");
pub const EDID: RecordType = RecordType::new(b"EDID");
pub const DATA: RecordType = RecordType::new(b"DATA");
pub const XEZN: RecordType = RecordType::new(b"XEZN");
pub const OBND: RecordType = RecordType::new(b"OBND");
pub const TX00: RecordType = RecordType::new(b"TX00");
pub const TX01: RecordType = RecordType::new(b"TX01");
pub const TX02: RecordType = RecordType::new(b"TX02");
pub const TX03: RecordType = RecordType::new(b"TX03");
pub const TX04: RecordType = RecordType::new(b"TX04");
pub const TX05: RecordType = RecordType::new(b"TX05");
pub const DODT: RecordType = RecordType::new(b"DODT");
pub const ICON: RecordType = RecordType::new(b"ICON");
pub const MICO: RecordType = RecordType::new(b"MICO");
pub const FULL: RecordType = RecordType::new(b"FULL");
pub const DESC: RecordType = RecordType::new(b"DESC");
pub const ATTR: RecordType = RecordType::new(b"ATTR");
pub const XNAM: RecordType = RecordType::new(b"XNAM");
pub const RNAM: RecordType = RecordType::new(b"RNAM");
pub const MNAM: RecordType = RecordType::new(b"MNAM");
pub const FNAM: RecordType = RecordType::new(b"FNAM");
pub const INAM: RecordType = RecordType::new(b"INAM");
pub const WMI1: RecordType = RecordType::new(b"WMI1");
pub const MODL: RecordType = RecordType::new(b"MODL");
pub const MODB: RecordType = RecordType::new(b"MODB");
pub const MODT: RecordType = RecordType::new(b"MODT");
pub const MODS: RecordType = RecordType::new(b"MODS");
pub const MODD: RecordType = RecordType::new(b"MODD");
pub const MOD2: RecordType = RecordType::new(b"MOD2");
pub const MO2T: RecordType = RecordType::new(b"MO2T");
pub const MO2S: RecordType = RecordType::new(b"MO2S");
pub const MOD3: RecordType = RecordType::new(b"MOD3");
pub const MO3T: RecordType = RecordType::new(b"MO3T");
pub const MO3S: RecordType = RecordType::new(b"MO3S");
pub const MOSD: RecordType = RecordType::new(b"MOSD");
pub const MOD4: RecordType = RecordType::new(b"MOD4");
pub const MO4T: RecordType = RecordType::new(b"MO4T");
pub const MO4S: RecordType = RecordType::new(b"MO4S");
pub const HNAM: RecordType = RecordType::new(b"HNAM");
pub const INDX: RecordType = RecordType::new(b"INDX");
pub const YNAM: RecordType = RecordType::new(b"YNAM");
pub const NAM2: RecordType = RecordType::new(b"NAM2");
pub const VTCK: RecordType = RecordType::new(b"VTCK");
pub const PNAM: RecordType = RecordType::new(b"PNAM");
pub const UNAM: RecordType = RecordType::new(b"UNAM");
pub const NAM0: RecordType = RecordType::new(b"NAM0");
pub const NAM1: RecordType = RecordType::new(b"NAM1");
pub const ENAM: RecordType = RecordType::new(b"ENAM");
pub const FGGS: RecordType = RecordType::new(b"FGGS");
pub const FGGA: RecordType = RecordType::new(b"FGGA");
pub const FGTS: RecordType = RecordType::new(b"FGTS");
pub const SNDD: RecordType = RecordType::new(b"SNDD");
pub const SNDX: RecordType = RecordType::new(b"SNDX");
pub const ANAM: RecordType = RecordType::new(b"ANAM");
pub const GNAM: RecordType = RecordType::new(b"GNAM");
pub const WNAM: RecordType = RecordType::new(b"WNAM");
pub const RDAT: RecordType = RecordType::new(b"RDAT");
pub const SLSD: RecordType = RecordType::new(b"SLSD");
pub const SCVR: RecordType = RecordType::new(b"SCVR");
pub const SCHR: RecordType = RecordType::new(b"SCHR");
pub const SCDA: RecordType = RecordType::new(b"SCDA");
pub const SCTX: RecordType = RecordType::new(b"SCTX");
pub const SCRO: RecordType = RecordType::new(b"SCRO");
pub const TNAM: RecordType = RecordType::new(b"TNAM");
pub const EFIT: RecordType = RecordType::new(b"EFIT");
pub const CTDA: RecordType = RecordType::new(b"CTDA");
pub const ENIT: RecordType = RecordType::new(b"ENIT");
pub const SPIT: RecordType = RecordType::new(b"SPIT");
pub const DSTD: RecordType = RecordType::new(b"DSTD");
pub const DMDL: RecordType = RecordType::new(b"DMDL");
pub const DMDT: RecordType = RecordType::new(b"DMDT");
pub const DSTF: RecordType = RecordType::new(b"DSTF");
pub const DEST: RecordType = RecordType::new(b"DEST");
pub const SCRI: RecordType = RecordType::new(b"SCRI");
pub const VNAM: RecordType = RecordType::new(b"VNAM");
pub const XATO: RecordType = RecordType::new(b"XATO");
pub const ITXT: RecordType = RecordType::new(b"ITXT");
pub const EITM: RecordType = RecordType::new(b"EITM");
pub const BMDT: RecordType = RecordType::new(b"BMDT");
pub const ICO2: RecordType = RecordType::new(b"ICO2");
pub const MIC2: RecordType = RecordType::new(b"MIC2");
pub const BMCT: RecordType = RecordType::new(b"BMCT");
pub const REPL: RecordType = RecordType::new(b"REPL");
pub const BIPL: RecordType = RecordType::new(b"BIPL");
pub const ETYP: RecordType = RecordType::new(b"ETYP");
pub const ZNAM: RecordType = RecordType::new(b"ZNAM");
pub const BNAM: RecordType = RecordType::new(b"BNAM");
pub const CNTO: RecordType = RecordType::new(b"CNTO");
pub const COED: RecordType = RecordType::new(b"COED");
pub const QNAM: RecordType = RecordType::new(b"QNAM");
pub const BRUS: RecordType = RecordType::new(b"BRUS");
pub const XRGD: RecordType = RecordType::new(b"XRGD");
pub const XRGB: RecordType = RecordType::new(b"XRGB");
pub const XPRD: RecordType = RecordType::new(b"XPRD");
pub const XPPA: RecordType = RecordType::new(b"XPPA");
pub const XLCM: RecordType = RecordType::new(b"XLCM");
pub const XMRC: RecordType = RecordType::new(b"XMRC");
pub const XCNT: RecordType = RecordType::new(b"XCNT");
pub const XRDS: RecordType = RecordType::new(b"XRDS");
pub const XHLP: RecordType = RecordType::new(b"XHLP");
pub const XDCR: RecordType = RecordType::new(b"XDCR");
pub const XLKR: RecordType = RecordType::new(b"XLKR");
pub const XCLP: RecordType = RecordType::new(b"XCLP");
pub const XADP: RecordType = RecordType::new(b"XADP");
pub const XAPR: RecordType = RecordType::new(b"XAPR");
pub const XESP: RecordType = RecordType::new(b"XESP");
pub const XEMI: RecordType = RecordType::new(b"XEMI");
pub const XMBR: RecordType = RecordType::new(b"XMBR");
pub const XIBS: RecordType = RecordType::new(b"XIBS");
pub const XSCL: RecordType = RecordType::new(b"XSCL");
pub const XOWN: RecordType = RecordType::new(b"XOWN");
pub const XRNK: RecordType = RecordType::new(b"XRNK");
pub const CARD: RecordType = RecordType::new(b"CARD");
pub const LNAM: RecordType = RecordType::new(b"LNAM");
pub const FLTV: RecordType = RecordType::new(b"FLTV");
